### ISSUE TITLE
Query: Latest Monaco Editor Versions and Snippets

### ISSUE THREAD

**Issue by khandelwalpiyush** [ngeenx/ngx-monaco-editor#1]
Hi

Looking at your fork.. Just had a few queries

- Would it automatically work with latest monaco-editor versions like 0.48.0 and above in future and latest Angular 17?
- Does [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) work on your build? Do you / can you do an example in your stackblitz code?

Thanks

**Comment by relliv** [comment]
@khandelwalpiyush hi, I didn't see your message sorry. I forked this repository for textmate implementation but I couldn't succeed. Now, I'm working on another angular monaco editor package. If the package matures, I will share it.

Theorically you can add your snippets over editor instance. See this [ref](https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.CompletionItemProvider.html).

BTW, if you want to fully featured and flexible solution don't use angular wrappers. Create your own implementations because such these third party packages are very limited. They just wrapping monaco editor and exporting.
